import turtle
def rectangle(color):
    t.begin_fill()
    t.fillcolor(color)
    for i in range(2):
        t.forward(400)
        t.right(90)
        t.fd(100)
        t.right(90)
    t.end_fill()

t=turtle.Turtle()
turtle.screensize(1400,1400)
turtle.title("National Flag of INDIA")
turtle.bgcolor("black")
t.pencolor("white")
t.speed(5)
t.hideturtle()
t.up()
t.pensize(4)
t.goto(0,-300)
t.down()

t.goto(0,300)
rectangle("orange")
t.goto(0,200)
rectangle("white")


t.goto(0,100)
rectangle("green")
t.home()
t.goto(0,-300)
t.begin_fill()
t.fillcolor("brown")
t.goto(0,200)
t.forward(200)
t.color("blue")
t.circle(-50)
t.setheading(270)
t.forward(50)
t.setheading(0)

for i in range( 24):
    t.forward(45)
    t.bk(45)
    t.left(15)
t.up()
t.home()
t.goto(0,-300)
t.down()
t.color("white")
t.begin_fill()
t.fillcolor("brown")

t.fd(100)
t.bk(200)
t.rt(90)
t.fd(50)
t.rt(90)
t.bk(200)
t.rt(90)
t.fd(50)
t.end_fill()
t.up()
t.setposition(200,-200)
t.pencolor("red")
t.write("Happy Independence Day!", font=(16))
